#!/usr/bin/env python3
"""
Build the biotools schema files.

This script generates the following files in dist/:
- biotools_vocab.py: one CHOICES-style list of (value, value) tuples per src/enums/*.json controlled vocabulary, for use as Django-style `choices=` arguments.
- biotools-<version>.xsd: the XML Schema Definition file, built from src/biotools.xsd.tmpl + src/enums/*.json.
- biotools-<version>.schema.json: the JSON Schema file, built from src/biotools.schema.tmpl.json + src/enums/*.json.
The template files contain placeholders that are replaced with the corresponding enum values from the controlled vocabularies in src/enums/*.json.

build_xsd() -> excludes deprecated values
build_jsonschema() -> excludes deprecated values
generate_vocab() -> INCLUDES deprecated values so existing bio.tools records remain representable

Usage:
    build-schema [--version <version>] [--output-dir <path>] [--only <vocab|xsd|jsonschema>]

"""

import argparse
import json
import re
from datetime import UTC, datetime
from pathlib import Path

from .build_utils import load_vocab_values, resolve_output_path

REPO_ROOT = Path(__file__).resolve().parents[1]
XSD_TEMPLATE_PATH = REPO_ROOT / "biotools.xsd.tmpl"
JSON_TEMPLATE_PATH = REPO_ROOT / "biotools.schema.tmpl.json"

XSD_PLACEHOLDER_RE = re.compile(
    r"^(?P<indent>[ \t]*)\{\{ENUM_XSD:(?P<vocab>[a-z_]+)\}\}$",
    re.MULTILINE,
)


### XSD BUILD


def render_enum_xsd(vocab: str, indentation: str) -> str:
    values = load_vocab_values(vocab)
    lines = [f'{indentation}<xs:enumeration value="{i}"/>' for i in values]
    return "\n".join(lines)


def build_xsd(version: str, output_dir: Path | None = None) -> Path:
    template = XSD_TEMPLATE_PATH.read_text(encoding="utf-8")
    print(
        f"building XSD from {XSD_TEMPLATE_PATH} with {len(XSD_PLACEHOLDER_RE.findall(template))} enum placeholders"
    )

    def replace(match):
        vocab = match.group("vocab")
        indentation = match.group("indent")
        return render_enum_xsd(vocab, indentation)

    rendered, count = XSD_PLACEHOLDER_RE.subn(replace, template)
    remaining = XSD_PLACEHOLDER_RE.findall(rendered)
    if remaining:
        raise RuntimeError(f"unresolved placeholders left in output: {remaining}")

    out_path = resolve_output_path(output_dir, f"biotools-{version}.xsd")

    out_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {out_path} ({count} enum placeholders resolved)")
    return out_path


### JSON SCHEMA BUILD


def _resolve_json_node(node: object, count: list[int]) -> object:
    if isinstance(node, dict):
        if "$enumRef" in node:
            vocab = node.pop("$enumRef")
            node["enum"] = load_vocab_values(vocab)
            count[0] += 1
            return node
        return {k: _resolve_json_node(v, count) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_json_node(v, count) for v in node]
    return node


def build_jsonschema(version: str, output_dir: Path | None = None) -> Path:
    template = json.loads(JSON_TEMPLATE_PATH.read_text(encoding="utf-8"))
    count = [0]
    rendered = _resolve_json_node(template, count)

    out_path = resolve_output_path(output_dir, f"biotools-{version}.schema.json")

    out_path.write_text(json.dumps(rendered, indent=4) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({count[0]} enum refs resolved)")
    return out_path


### VOCAB
# vocab file stem -> generated variable name
VAR_NAMES = {
    "language": "LANGUAGE",
    "license": "LICENSE",
    "operating_system": "OPERATING_SYSTEM",
    "tool_type": "TOOL_TYPE",
    "maturity": "MATURITY",
    "cost": "COST",
    "accessibility": "ACCESSIBILITY",
    "elixir_platform": "ELIXIR_PLATFORM",
    "elixir_community": "ELIXIR_COMMUNITY",
    "elixir_node": "ELIXIR_NODE",
    "other_id_type": "OTHER_ID_TYPE",
    "link_type": "LINK_TYPE",
    "download_type": "DOWNLOAD_TYPE",
    "documentation_type": "DOCUMENTATION_TYPE",
    "relation_type": "RELATION_TYPE",
    "publication_type": "PUBLICATION_TYPE",
    "credit_type_entity": "CREDIT_TYPE_ENTITY",
    "credit_type_role": "CREDIT_TYPE_ROLE",
}


def render_choices(vocab: str, var_name: str) -> str:
    ids = load_vocab_values(vocab, include_deprecated=True)
    lines = [f"{var_name} = ["]
    lines += [f"    ({value!r}, {value!r})," for value in ids]
    lines.append("]")
    return "\n".join(lines)


def generate_vocab(output_dir: Path | None = None) -> Path:
    out_path = resolve_output_path(output_dir, "biotools_vocab.py")

    now = datetime.now(UTC).isoformat()
    header = (
        f'"""AUTO-GENERATED by github.com/bio-tools/biotoolsSchema/scripts/build.py at {now}.\n\n'
        'Do not edit by hand.\n"""\n\n'
    )
    blocks = [render_choices(vocab, var) for vocab, var in VAR_NAMES.items()]
    out_path.write_text(header + "\n\n\n".join(blocks) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(VAR_NAMES)} choice lists)")
    return out_path


def build():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default="dev")
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument(
        "--only",
        choices=("all", "vocab", "xsd", "jsonschema"),
        default="all",
    )
    args = parser.parse_args()

    if args.only in ("all", "vocab"):
        generate_vocab(args.output_dir)
    if args.only in ("all", "xsd"):
        build_xsd(args.version, args.output_dir)
    if args.only in ("all", "jsonschema"):
        build_jsonschema(args.version, args.output_dir)


if __name__ == "__main__":
    build()
